<style>
.onlineimg {
    background-position: -212px -116px;
    height: 7px;
    width: 7px;
}
#onlinebox {
    background-color: #E9EAED;
    border: 1px solid #CCCCCC;
    bottom: 30px;
    color: #333333;
    font-family: arial,sans-serif;
    font-size: 13px;
    height: auto;
    line-height: 1.3em;
    overflow: auto;
    /*padding: 7px;*/
    position: fixed;
    right: 0;
    width: 13%;
    z-index: 991;
}
.onlineboxhead {
	padding: 7px;
	 background-color: #0072B1;
	 width:100%;
}
#accordion{
	padding: 7px;
	display:none;
}
a:hover{
	cursor:pointer;
}

.chatbox{
	background-color: #E9EAED;
    border: 1px solid #CCCCCC;
    bottom: 30px;
    color: #333333;
    font-family: arial,sans-serif;
    font-size: 13px;
    height: auto;
    line-height: 1.3em;
    overflow: auto;
    right: 0;
    z-index: 991;
} 
ol, ul {
padding:0px;
}
ol, ul, li{
list-style:outside none none;
}
</style>
<script >
var Touser = "";
               var 	Tousername="";
              var   c = "";		

$(function() {
			var idusersession = document.getElementById('iduser').value;
		});
		
		
	$(function() {
		
		$( "#onlineboxhead" ).click(function() {
			$( "#accordion" ).toggle();
		});
		
	});
	function fetchmessage(Touser,Tousername,flag){ 
	
			Touser = document.getElementById('Currenttouser').value;
			Tousername = document.getElementById('Currenttousername').value;
			
			       if(chatUsers != ''){
					var me = document.getElementById('iduser').value;
					var timestamp = 1;					
					var track_click = 0; 
			       tabledata = '';			
			        typeofchat = 1;
					jQuery.ajax({
							type: "POST",
							url: "loadallmessages.php",
							data:  { me: me, Idusersto: Touser,name: Tousername,track_click: track_click } ,
							cache: false,			
							success: function(html){
							//alert(html);
					var obj = JSON.parse(html);
					//console.log(obj);					
					var countarray = obj.length;					
					//alert(countarray);
					tabledata += '<div id = "msg"+Touser style = "width:100%;">';
					if(html != 0){
					
							for(i=0;i<countarray;i++){

								str = Tousername;
								Idusers = obj[i]['from'];
								if(me == Idusers){
									
									names = "me";
									
								}else{
									names = String(str);
								
								}
								msg = obj[i]['message'];
								
								tabledata += '<div class="chatboxmessage"><span class="chatboxmessagefrom">'+names+':&nbsp;&nbsp;</span><span class="chatboxmessagecontent">'+msg+'</span></div>';
								
							}
					}else{
						tabledata += 'No conversation happened';
						$("#msg"+Touser).fadeOut(3000);
					}	
						
					tabledata += '</div>';
					document.getElementById("label"+Touser).innerHTML = '';
					document.getElementById("msg"+Touser).innerHTML = tabledata;
				}
					});
					
					
					
				}
			
			}
	var windowFocus = true;
	 var username;
	 var chatHeartbeatCount = 0;
	 var minChatHeartbeat = 1000;
	 var maxChatHeartbeat = 33000;
	 var chatHeartbeatTime = minChatHeartbeat;
	 var originalTitle;
	 var blinkOrder = 0;
	 var chatboxFocus = new Array();
	 var newMessages = new Array();
	 var newMessagesWin = new Array();
	 var chatBoxes = new Array();
	 var chatUsers = new Array();
	 var statusofminimize = 0;
	  var msg = '';
	   var Currentuser;
	 
	function chatWith(Idusersto,chatuser,msg,idrole,typeflag){
		value  = chatuser.substr(0,chatuser.indexOf(' ')); 
		if(value != ''){
			chatuser = value;
		}else{
			chatuser = chatuser;
		}		
		createChatBox(Idusersto,chatuser,msg,idrole,typeflag);
		//var Currenttouser = Idusersto;			
	}	
	function createChatBox(Idusersto,chatboxtitle,msg,idrole,typeflag,minimizeChatBox){
	
		var me = document.getElementById('iduser').value;
		
				if($("#chatbox_"+chatboxtitle).length > 0){
					if ($("#chatbox_"+chatboxtitle).css('display') == 'none') {
						$("#chatbox_"+chatboxtitle).css('display','block');
						if(idrole==4)
						restructureChatBoxes();
					}
					return;
				}
				
				$("<div/>" ).attr("id","chatbox_"+chatboxtitle)
				.addClass("chatbox")
				.html('<input type = "hidden" name = "Currenttousername" id = "Currenttousername" value = "'+chatboxtitle+'"><input type = "hidden" name = "Currenttouser" id = "Currenttouser" value = "'+Idusersto+'"><a style="color:#ffffff" href="javascript:void(0)" onclick="javascript:toggleChatBoxGrowth(\''+chatboxtitle+'\')"><div class="chatboxhead" ><div class="chatboxtitle" style="color:#ffffff">'+chatboxtitle+'</div>'+
					'<div class="chatboxoptions">&nbsp;-&nbsp;'+
					
					'<a  href="javascript:void(0)" onclick="javascript:closeChatBox(\''+chatboxtitle+'\','+idrole+')">X</a>'+
					'</div></a><br clear="all"/></div><div class="chatboxcontent"><div  id  = "show'+Idusersto+'" style="display:flex;"></div>'+
					'<div style="display:flex;"  id = "msg'+Idusersto+'"></div>'+
					'<div id = "label'+Idusersto+'" style="display:flex;" >'+
					'<a href = "#"></a>'+
					'</div>'+
					'</div>'+
					'<div class="chatboxinput"><textarea class="chatboxtextarea" id="chatboxtextarea" onkeydown="javascript:return checkChatBoxInputKey(event,this,\''+chatboxtitle+'\',\''+Idusersto+'\',1);"></textarea></div>')
				.appendTo($( "body" ));			
			
				if(idrole==4){
					$("#chatbox_"+chatboxtitle).css('bottom', '30px');
					chatBoxeslength = 0;
					for(x in chatBoxes){
						if ($("#chatbox_"+chatBoxes[x]).css('display') != 'none'){
							chatBoxeslength++;
						}
					}if(chatBoxeslength == 0){
						$("#chatbox_"+chatboxtitle).css('right', '190px');
					}else{
						width = (chatBoxeslength)*(225+7)+190;
						$("#chatbox_"+chatboxtitle).css('right', width+'px');
					}
					
				}
				var Touser = Idusersto;
               	var Tousername=chatboxtitle;						
					chatBoxes.push(chatboxtitle);
					chatUsers.push(Idusersto);
					
					chatboxFocus[chatboxtitle] = false;
					$("#chatbox_"+chatboxtitle+" .chatboxtextarea").blur(function(){
						chatboxFocus[chatboxtitle] = false;
						$("#chatbox_"+chatboxtitle+" .chatboxtextarea").removeClass('chatboxtextareaselected');
						//$('#chatbox_'+chatboxtitle+' .chatboxhead').removeClass('chatboxblink');
					}).focus(function(){
						chatboxFocus[chatboxtitle] = true;
						newMessages[chatboxtitle] = false;
						$('#chatbox_'+chatboxtitle+' .chatboxhead').removeClass('chatboxblink');
						$("#chatbox_"+chatboxtitle+" .chatboxtextarea").addClass('chatboxtextareaselected');
					});
					$("#chatbox_"+chatboxtitle).click(function(){
						$('#chatbox_'+chatboxtitle+' .chatboxhead').removeClass('chatboxblink');
						if ($('#chatbox_'+chatboxtitle+' .chatboxcontent').css('display') != 'none') {
						}
					});	
			$("#chatbox_"+chatboxtitle).show();
			flag=1;
			setInterval(function(){fetchmessage(Touser,Tousername,flag);}, 1000);
	}
	function toggleChatBoxGrowth(chatboxtitle){
		
			if ($('#chatbox_'+chatboxtitle+' .chatboxcontent').css('display') == 'none') {  
				var minimizedChatBoxes = new Array();
				if ($.cookie('chatbox_minimized')){
					minimizedChatBoxes = $.cookie('chatbox_minimized').split(/\|/);
				}
				var newCookie = '';
				for (i=0;i<minimizedChatBoxes.length;i++) {
					if (minimizedChatBoxes[i] != chatboxtitle){
						newCookie += chatboxtitle+'|';
					}
				}
				newCookie = newCookie.slice(0, -1)
				$.cookie('chatbox_minimized', newCookie);
				$('#chatbox_'+chatboxtitle+' .chatboxcontent').css('display','block');
				$('#chatbox_'+chatboxtitle+' .chatboxinput').css('display','block');
				$("#chatbox_"+chatboxtitle+" .chatboxcontent").scrollTop($("#chatbox_"+chatboxtitle+" .chatboxcontent")[0].scrollHeight);
			}else{
				var newCookie = chatboxtitle;
				if ($.cookie('chatbox_minimized')) {
					newCookie += '|'+$.cookie('chatbox_minimized');
				}
				$.cookie('chatbox_minimized',newCookie);
				$('#chatbox_'+chatboxtitle+' .chatboxcontent').css('display','none');
				$('#chatbox_'+chatboxtitle+' .chatboxinput').css('display','none');
			}
		}
		jQuery.cookie = function(name, value, options) {
			if (typeof value != 'undefined') { // name and value given, set cookie
				options = options || {};
				if (value === null) {
					value = '';
					options.expires = -1;
				}
				var expires = '';
				if (options.expires && (typeof options.expires == 'number' || options.expires.toUTCString)) {
					var date;
					if (typeof options.expires == 'number') {
						date = new Date();
						date.setTime(date.getTime() + (options.expires * 24 * 60 * 60 * 1000));
					} else {
						date = options.expires;
					}
					expires = '; expires=' + date.toUTCString(); // use expires attribute, max-age is not supported by IE
				}
				// CAUTION: Needed to parenthesize options.path and options.domain
				// in the following expressions, otherwise they evaluate to undefined
				// in the packed version for some reason...
				var path = options.path ? '; path=' + (options.path) : '';
				var domain = options.domain ? '; domain=' + (options.domain) : '';
				var secure = options.secure ? '; secure' : '';
				document.cookie = [name, '=', encodeURIComponent(value), expires, path, domain, secure].join('');
			}else { // only name given, get cookie
				var cookieValue = null;
				if (document.cookie && document.cookie != '') {
					var cookies = document.cookie.split(';');
					for (var i = 0; i < cookies.length; i++) {
						var cookie = jQuery.trim(cookies[i]);
						// Does this cookie string begin with the name we want?
						if (cookie.substring(0, name.length + 1) == (name + '=')) {
							cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
							break;
						}
					}
				}
				return cookieValue;
			}
		};
	function restructureChatBoxes(){
			align = 0;
			for (x in chatBoxes) {
				chatboxtitle = chatBoxes[x];
				if ($("#chatbox_"+chatboxtitle).css('display') != 'none') {
					if (align == 0) {
						$("#chatbox_"+chatboxtitle).css('right', '190px');
					} else {
						width = (align)*(225+7)+190;
						console.log(width+"outside");
						$("#chatbox_"+chatboxtitle).css('right', width+'px');
					}
					align++;
				}
			}
		}		
		function closeChatBox(chatboxtitle,idrole){
			//alert(idrole);
			$('#chatbox_'+chatboxtitle).css('display','none');
			if(idrole==4)
			restructureChatBoxes();
		}
		function checkChatBoxInputKey(event,chatboxtextarea,chatboxtitle,Idusersto,typeflag){
		var fromuser='<?php echo $_SESSION['iduser']; ?>';
			$('#chatbox_'+chatboxtitle+' .chatboxhead').removeClass('chatboxblink');
			if(typeflag == 1){
				if(event.keyCode == 13 && event.shiftKey == 0){
					var iduser = document.getElementById('iduser').value;
					var membername = document.getElementById('membername').value;
					var username = membername;
					message = $(chatboxtextarea).val();
					message = message.replace(/^\s+|\s+$/g,"");
					$(chatboxtextarea).val('');
					$(chatboxtextarea).css('height','44px');
					if(message != '')
					   {
					   
						$.ajax({
								type: "POST",
								url: 'chatmessages.php',
								data: {from:fromuser,to: Idusersto,message: message},
								cache: false,	
								success: function(data){
								   //$("#chatbox_"+chatboxtitle+" .chatboxcontent").append('<div class="chatboxmessage"><span class="chatboxmessagefrom">'+username+':&nbsp;&nbsp;</span><span class="chatboxmessagecontent">'+message+'</span></div>');
									//$("#chatbox_"+chatboxtitle+" .chatboxcontent").append('<div class="chatboxmessage"><span class="chatboxmessagefrom">me:&nbsp;&nbsp;</span><span class="chatboxmessagecontent">'+message+'</span></div>');
									$("#chatbox_"+chatboxtitle+" .chatboxcontent").scrollTop($("#chatbox_"+chatboxtitle+" .chatboxcontent")[0].scrollHeight);
									
								}
							  });
					   }
					
					chatHeartbeatTime = minChatHeartbeat;
					chatHeartbeatCount = 1;
					return false;
				}
			 }else{
				 
				if(chatboxtextarea != ''){
					var username = name;
					message = 	chatboxtextarea;
					$("#chatbox_"+chatboxtitle+" .chatboxcontent").append('<div class="chatboxmessage"><span class="chatboxmessagefrom">'+username+':&nbsp;&nbsp;</span><span class="chatboxmessagecontent">'+message+'</span></div>');
				}
			 }
			 var adjustedHeight = chatboxtextarea.clientHeight;
			 var maxHeight = 94;
			 if (maxHeight > adjustedHeight) {
				adjustedHeight = Math.max(chatboxtextarea.scrollHeight, adjustedHeight);
				if (maxHeight)
					adjustedHeight = Math.min(maxHeight, adjustedHeight);
				if (adjustedHeight > chatboxtextarea.clientHeight)
					$(chatboxtextarea).css('height',adjustedHeight+8 +'px');
			 }else{
				$(chatboxtextarea).css('overflow','auto');
			 }
		}
		
</script>
<?php  
	 $collection = $conn->tbl_profile;	
	 $larresult = $collection->findOne(array('_id' => $_SESSION['iduser']));
 ?>
 <?php if($larresult['Typeofuser']==1){ ?>
<div id="onlinebox" >
	<div class="onlineboxhead" id="onlineboxhead">Chat With Case Worker</div>
	<div id="accordion">
		<ul>
				<li>
					
						 <?php
		                            $profilecolln = $conn->tbl_profile;									
                                    $larrresult = $profilecolln->findOne(array('_id' => new MongoId($_SESSION['iduser'])));                                    
									if($larrresult['Typeofuser'] ==1)
									{
											   //$pcollection = $conn->tbl_profile;	
											   $result = $profilecolln->find(array('Typeofuser' =>'2'));
									}
                                   foreach($result as $item)
								    { ?>
                                    <span><img src="./images/online.gif" style="width:10px;height:10px"></span>								
					                <a id="1" onclick="chatWith('<?php echo $item['_id']; ?>','<?php echo $item['Name']; ?>',msg,4,1)" value="1">
								    <?php echo $item['Name']; ?><br/>
							        </a>
									<?php
									}
									?>									
							
						</li>
		</ul>
		<input type = 'hidden' name = 'idchatuser' id = 'idchatuser' value = ''>
		<input type = 'hidden' name = 'namechatuser' id = 'namechatuser' value = ''>
		<input type = 'hidden' name = 'iduser' id = 'iduser' value = '<?php echo $_SESSION['iduser'];?>'>
		<input type = 'hidden' name = 'membername' id = 'membername' value = 'Guru'>
	</div>
</div>
<?php }else{ ?>
<div id="onlinebox" >
	<div class="onlineboxhead" id="onlineboxhead">Chat With Parents</div>
	<div id="accordion">
		<ul>
				<li>
					
							<?php
		                            $profilecolln = $conn->tbl_profile;									
                                    $larrresult = $profilecolln->findOne(array('_id' => new MongoId($_SESSION['iduser'])));                                    
									if($larrresult['Typeofuser'] ==2)
									{
											   //$pcollection = $conn->tbl_profile;	
											   $result = $profilecolln->find(array('Typeofuser' =>'1'));
									}
                                   foreach($result as $item)
								    { ?>
                                    <span><img src="./images/online.gif" style="width:10px;height:10px"></span>								
					                <a id="1" onclick="chatWith('<?php echo $item['_id']; ?>','<?php echo $item['Name']; ?>',msg,4,1)" value="1">
								    <?php echo $item['Name']; ?><br/>
							        </a>
									<?php
									}
									?>	
						</li>
		</ul>
		<input type = 'hidden' name = 'idchatuser' id = 'idchatuser' value = ''>
		<input type = 'hidden' name = 'namechatuser' id = 'namechatuser' value = '<?php echo $_SESSION['iduser'];?>'>
		<input type = 'hidden' name = 'iduser' id = 'iduser' value = '<?php echo $_SESSION['iduser'];?>'>
		<input type = 'hidden' name = 'membername' id = 'membername' value = 'harsha'>
	</div>
</div>
<?php } ?>